### ISSUE TITLE
IP type display

### ISSUE THREAD

**Issue by frnkblk** [adolfintel/speedtest#102]
Is it possible to show both IPv4 and IPv6, if the tester is dual-stacked, and also indicate in the test which protocol is being used?  Even better would be for both protocols to be speed tested.

**Comment by adolfintel** [comment]
If the tester has multiple addresses, the server can only know the address from which the request came from. This is the address that's returned by getIP.php.

If you want to do that, the solution is not very simple and will not be implemented in this test because it would be too complicated for users to set up:
* You need a server that's reachable only via IPv4 and one that's only reachable via IPv6, otherwise you have no choice over which connection the client's browser will use (complicated, possibly expensive)
* You need to modify the front end to make XHR requests to getIP.php on both servers and display the output (This is the only part that I can do)
* You need to set up your server to send CORS headers for those cross-domain requests (complicated)

So, if this is what you need, I'm afraid this project is not for you.

**Comment by frnkblk** [comment]
Didn't say it was going to be easy. ;)

Have a merry Christmas,

Frank
