### ISSUE TITLE
test IPv6 and IPv4 with one interface

### ISSUE THREAD

**Issue by genofire** [adolfintel/speedtest#103]
Test both with settings for different urls (domains with only A and AAAA records)

RFC:
it would be nice to have one web interface to test both ipv4 and ipv6 in a row.

**Comment by adolfintel** [comment]
This would be a nice feature to have; unfortunately, as I've already explained in other issues who suggested it, when the system has more than 1 connection available, at the moment it's the browser that chooses which one to use, I have no control over it.
The only way you can force that is to have 2 separate servers (or 2 subdomains with properly configured A and AAAA records), one that only supports IPv4 and one that only supports IPv6. You host the test on both servers then make a page with 2 iframes and a simple script that detects if one of the iframes fails to load because that type of connection is not available and starts the tests one after the other.

**Comment by genofire** [comment]
you are correct with two dns records for both ip address.
But both records could point on the same server and the same webpage (like this speedtest)

You did not have to use any iframe or any rubish:
https://github.com/genofire/speedtest/commit/d273a334e9c10cb5e98b1048db10d705ff5f1cb0

**Comment by adolfintel** [comment]
ipv6.speedtest.sum7.eu and ipv4.speedtest.sum7.eu are different domains, I assume your server is set to send CORS headers?

**Comment by genofire** [comment]
Of course - origin http://speedtest.sum7.eu https://speedtest.sum7.eu and allowed_headers *

**Comment by adolfintel** [comment]
Good work, that's better than using the iframes. I proposed that solution because it required no changes to the code (a lot of people here if you look at the past issues have 0 coding skills).
I'll keep a link to your version of the test in case someone else needs it.

**Comment by genofire** [comment]
I have thought about something like this.

But i have still some problems:
- upload over cors on firefox did not work (on chrome just works with cors header content-encoding/*)
- failed handling it ipv6.speedtest.sum7.eu (the url is not reachable)

**Comment by adolfintel** [comment]
In all honesty, I don't know. There's a good chance that this is one of those weird issues caused by the web worker. Some XHR headers and events seem to behave erratically. I'm thinking of getting rid of the worker, although it might cause the UI to lag quite a bit.
