### ISSUE TITLE
Configurable default filesize for garbage download

### ISSUE THREAD

**Issue by bplower** [adolfintel/speedtest#131]
I'm in a situation where I would like to change the default filesize for the download in garbage.php. At the moment, it's hardcoded to 4 megabytes. The change would look something like:

```php
include_once('settings.php');
...
$default_chunks = 4;
$chunks=isset($_GET['ckSize']) ? intval($_GET['ckSize']) : $default_chunks;
if(empty($chunks)){$chunks = $default_chunks;}
```

This would necessitate the creation of a new settings file, since this configuration isn't related to telemetry. Multiple settings files isn't ideal though, so I think it would be better to rename `telemetry_settings.php` to `settings.php`.

It's all pretty straightforward, but I wanted to get your thoughts on it before opening a PR.

**Comment by marioaldayuz** [comment]
Reasonable.   
  

  
  

  
  
>

**Comment by adolfintel** [comment]
Hi,
The setting can be easily changed via script when starting the test; see the section on custom settings in doc.md and example-customSettings.html.

Also, please note that changing the size of this download has no effect on the duration of the test, because it's time based; if you want to make the test longer or shorter, there are parameters for that too.

**Comment by adolfintel** [comment]
And about settings_telemetry.php, that one has to be separate from the other test settings, since it contains your db credentials.
