### ISSUE TITLE
test hangs if server can't make outbound calls

### ISSUE THREAD

**Issue by randallt** [adolfintel/speedtest#134]
I first installed this on a server that could not make outbound https calls (corporate proxy). The UI just appears to hang while that attempt is made (and finally times out). It would be good if the ISP detection could fail fast (1 sec), or if the ISP detection could happen client side somehow.

**Comment by adolfintel** [comment]
The ISP detection could be moved to the client but I do it server side because otherwise, you must send CORS headers to the client when the page is loaded. CORS headers are a bit wonky in many browsers, and most people don't even know they exist or how to enable them on their server, which is why I prefer to do it server side, to avoid getting a million people asking me how to enable them.
An option to do it client side may be added in the future but for now, with people still needing IE11 support, no way.

For your use case, since it can't access the ipinfo service, I suggest you just turn off ISP detection with the ```getIp_ispInfo``` parameter.

**Comment by randallt** [comment]
It might help others to mention in the doc that if they see a pause after pushing start, then they might be hitting this issue. It took me awhile to debug it.

**Comment by Victor-D** [comment]
Hi,

Yes if the TCP SYN goes out without TCP RST or if the SYN-ACK is blocked then the connection is stucked until the TCP timeout.

It's a sydadmin issue not related to your speedtest project.

If I was in this case, and without the need of telemetry, I would set an entry 
127.0.0.1 ipinfo.io
in the server /etc/hosts file to force a quick connection failure.

Nevertheless client side implementation in javascript is a good idea.
In addition, the ipinfo.io public service would not see only the server ip which may be better to avoid hitting request number limit (if there is).

**Comment by adolfintel** [comment]
The problem with client side is that CORS headers thing.
It looks easy but it's wonky as hell, because the standard doesn't specify if the Worker should get those privileges or not, so different browsers act differently, even different versions of the same browser.
Chromium is the only one that seems to have done it right.
