### ISSUE TITLE
Speed Limit

### ISSUE THREAD

**Issue by wwwadminmd** [adolfintel/speedtest#140]
Hello, very nice and useful project, thank you so much for what you are doing for us.
  I have 3 servers in the same datacenter.  Connection is 1Gb/s. One is Windows based, Second is speedtest.net relay and the third is A linux server with your project hosted. (speedtest.md).
 When I test with speedtest.net project, from Win PC in the same datacenter I get 920+ Mb/s, but when I test with your project I get only 350-450Mb.
 I think that speedtest_worker.js is the problem:). Did you test it on 1Gb/s connection?
Thanks in advice.

**Comment by adolfintel** [comment]
Yes, this was tested with a gigabit connection.
The problem you're experiencing is simply the client being too slow to run the javascript fast enough. This can be caused by a number of reasons: weak CPU, hardware acceleration turned off or not working, some antivirus software, ...

**Comment by wwwadminmd** [comment]
I have 8 Xeon Cores and 96 GB Ram EEC DDR3 1600Mhz, this is not SLOW CLIENT LOL_

**Comment by wwwadminmd** [comment]
http://prntscr.com/k0pz5y

**Comment by adolfintel** [comment]
Ok that's definitely not slow 😂 
Can you make sure that hardware acceleration is enabled in chrome? If it's turned off it can screw up measurements on fast connections like this.

**Comment by wwwadminmd** [comment]
http://prntscr.com/k0q0fk - Same data center
http://prntscr.com/k0q0zk - Results a different

**Comment by wwwadminmd** [comment]
When I test with speedtest.net from the same DC I get 800mb/s. When I test with this project on the same DC I get only 50% (

I can offer access to both, Client and Server to your team for testing purposes.

**Comment by adolfintel** [comment]
The ookla speedtest is not affected by this timing issue because it uses websockets. My test uses XHR because it makes it a lot easier to install and run.
All I can say is that in a normal scenario, I've seen it go up to 4-5 gbps on my i7 desktop without problems, so 1gbps definitely shouldn't be an issue.
Maybe the fact that you're streaming the screen with RDP is causing some lag in chrome?

If you want to look a bit further into this, here's a few things you can try:
* Make sure you don't have a firewall or something that throttles HTTP when multiple parallel connections are performed
* Try changing the test's xhr_dlMultistream and xhr_ulMultistream to higher or lower values (defaults of 10 and 3 respectively). 1 and 1 are the "safest" values that usually won't trigger any firewall or throttling
* Try changing the test's garbagePhp_chunkSize to a higher value (default is 20)
* Last, try performing the test from a "normal" scenario, without RDP and where you know that hardware acceleration works

If that still doesn't solve your problem, I'm really out of ideas.

**Comment by wwwadminmd** [comment]
I set all values and perform all actions as you said. But I cant see any several changes. 
Thank you so much for you full answer and help. I really appreciate that.

**Comment by adolfintel** [comment]
Still the same? Are you 100% sure that hardware acceleration is working in chrome? 
If you run these [webgl demos](https://experiments.withgoogle.com/collection/chrome) like [this one](https://paveldogreat.github.io/WebGL-Fluid-Simulation/) the CPU usage doesn't skyrocket?

**Comment by dunklesToast** [comment]
When I do your hosted test from my Server (~1 Gbit) it worked fine. Maybe its something with Windows Server. I dont think that Hardware Acceleration would solve this since Server usually have no GPU and HW Acceleration uses the GPU, right? Can you post a screenshot of your network tab in the Chrome Developer Tools?

**Comment by adolfintel** [comment]
I suspect that too. That server looks like a virtual machine, it may not have hardware acceleration

**Comment by dunklesToast** [comment]
@wwwadminmd Can you please try to do a speedtest here: http://speed.dunklestoast.de/
And please post a screenshot from the result here!

**Comment by adolfintel** [comment]
@dunklesToast check the link, I'm getting a bad gateway error

**Comment by dunklesToast** [comment]
whoops. forgot to start it via pm2 - fixed!

**Comment by dunklesToast** [comment]
hmm. The error 413 could be the problem. Your Server seems to be to fast / sends to big packets. Maybe tweaking the webserver config (IIS, nginx, apache etc.) could help there.
NGINX has this option for server blocks: `client_max_body_size 100M;`
Do you have the same error when using the PHP Version (speed.dunklestoast.de uses the nodeJS Port)

**Comment by adolfintel** [comment]
Nah, he got the error after the data was sent. Besides, those are the upload test requests.
He should increase the POST size to remove the 413 but it's not mandatory

On June 29, 2018 12:31:33 PM GMT+02:00, Tom <notifications@github.com> wrote:
>hmm. The error 413 could be the problem. Your Server seems to be to
>fast / sends to big packets. Maybe tweaking the webserver config (IIS,
>nginx, apache etc.) could help there.
>NGINX has this option for server blocks: `client_max_body_size 100M;`
>Do you have the same error when using the PHP Version
>(speed.dunklestoast.de uses the nodeJS Port)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/speedtest/issues/140#issuecomment-401316367

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wwwadminmd** [comment]
Increased Post Size at 100M. Same results..

**Comment by wwwadminmd** [comment]
Thanks all for replies, I contact the Data Center and we almost find out who are limiting the speed. Problem is that the site is hosted on VPS that shares internet connection with other VPS`es. 1Gb/s - but it is shared between many virtual servers.
I will change the server with a dedicated one, and after that I will come here with results.
Thanks a lot for all team!

**Comment by kodewa** [comment]
I was tested on local server connected to Gbic switch results only 100 Mbps.

**Comment by adolfintel** [comment]
@kodewa 
I assure you, if the speedtest had such a massive limitation, I would never have released it ;)
Something between you and the server is throttling HTTP (or the server itself). You'll have to investigate this, or at least give me some more info about your setup.
