### ISSUE TITLE
Feature Request: Parallel Upload & Download

### ISSUE THREAD

**Issue by schlomo** [adolfintel/speedtest#148]
ATM the speedtest first performs the download and then the upload. Would it be possible to perform those transfers in parallel at the same time?

My goal is to check the speed for video conferencing where both traffic directions matter, especially concurrently.

Also, I expect the results to be lower due to the many ACK packages that share the bandwidth with the payload data. That should be much more realistic for concurrent up/download use cases like video conferencing.

**Comment by schlomo** [comment]
So the development happens now mostly on the nodeJS version?

**Comment by dunklesToast** [comment]
No. But I just maintain the node version and can’t say what @adolfintel is going to add to the php version (which he maintains)

**Comment by adolfintel** [comment]
I could add a combined test in the speedtest worker. This doesn't require anything special on either the PHP or node backend, it's just JS.
I can't tell you when exactly when I'll be doing this because right now I'm working on implementing multiple points of test (having multiple speedtest servers around the world and choosing the nearest one), which was requested a lot more frequently.
If you want it now, there's an easy way of doing this:
* In your frontend HTML, have 2 instances of speedtest_worker
* configure the first one to do only the download test
* configure the second one to do only the upload test (and then if you want, the ping test, etc.)
* start the 2 workers together
You won't be able to use the telemetry with this trick, but you'll have a combined test.

Anyway, I'll add this to my todo list, a proper combined test will come.

**Comment by schlomo** [comment]
Thanks a lot, could you update this issue once it is available?

**Comment by adolfintel** [comment]
Sure thing

**Comment by realies** [comment]
As far as I understand, this does not seem available in the sense that speedtest.net can do it. Meaning that there would be multiple download connections while the download metric is generated, and similarly while the upload metric is generated.

Can someone confirm? cc @adolfintel
