### ISSUE TITLE
Feature Request for Multiple Points of Test

### ISSUE THREAD

**Issue by History73** [adolfintel/speedtest#151]
Hi,
a) Can you add one option if someone need to change server manually?
b)If someone knows the path of the files on the backend server they can run a test from their site using my own backend server.There is a way he can not do that?

**Comment by adolfintel** [comment]
>Can you add one option if someone need to change server manually?
I was working on adding an example with manual server selection this morning. It's coming tomorrow I think. It's not really a feature, it's just a UI thing.

>If someone knows the path of the files on the backend server they can run a test from their site using my own backend server.There is a way he can not do that?
If someone knows the path to your backend servers they can run a test from their own site, yes. You can avoid that if you edit garbage.php, empty.php and getIP.php and replacing
```
header('Access-Control-Allow-Origin: *');
```
with a list of allowed servers instead of *. More about CORS headers [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)
I didn't do this myself because if I did someone would open an issue every 5 minutes telling me that the examples don't work.

**Comment by adolfintel** [comment]
I just added the example
