### ISSUE TITLE
Different result on pretty and gauges.html

### ISSUE THREAD

**Issue by nbctcp** [adolfintel/speedtest#166]
## Description
Using example-pretty.html got download 150MB
Using example-gauges.html got 100MB
Why different result?

## Server
-latest Kali Linux 2018 on vmWare Workstation 14
-apache2

## Client
-opera on pc host windows 10

## Steps to reproduce
# cd /var/www/html/speedtest
# cp example-pretty.html index.html
open http://kaliip/speedtest from parent pc opera
got download 150MB
# cp example-gauges.html index.html
open http://kaliip/speedtest from parent pc opera
got download 100MB

## Expected behaviour
I think it should be the same result right?
tq

**Comment by adolfintel** [comment]
That's a new one.
The 2 examples are running the same speedtest code so that's probably not where the problem lies.
You may have a problem with hardware acceleration on opera. Try this:
* Run the 2 versions again
* This time, keep an eye on the task manager
* Do you see a higher CPU usage when running the gauges example? (Could be a single core running at 100% or multiple cores with moderately high usage)

Also, what kind of hardware do you have on your client machine?

**Comment by nbctcp** [comment]
INFO:
Dell laptop with 1x CPU i5-4200 2 cores 16GB RAM
webserver Apache2 run on vm in vmWare Workstation 14 on top of Windows 10
vm allocated cpu 1 socket 2 cores, ram 2gb

1. example-gauges.html and example-pretty.html will both spike CPU from 13% to 100%

**Comment by adolfintel** [comment]
Is the VM on the same machine?

**Comment by nbctcp** [comment]
yes.
so I think there are no traffic going to router and comeback because same subnet

**Comment by adolfintel** [comment]
Ok, that's the problem.
If the server and client are on the same machine, you're basically trying to measure the speed of your loopback interface, which is super fast and of course CPU usage goes up to 100%, which is what causes the incorrect results because it messes up timing.
If you run the VM on another machine, you shouldn't have this problem. You might still see a relatively high CPU usage since your machine isn't super fast though.
