### ISSUE TITLE
Firefox [Upload test] bug w/ loading bar

### ISSUE THREAD

**Issue by 649** [adolfintel/speedtest#177]
## Description
If we run a normal test on Firefox, for some reason the upload test takes much longer than usual to initiate compared to other browsers like Edge, causing the loading bar to escape and also cause inaccurate upload speeds to be calculated. I've provided screenshots for further assessment.

## Server
Apache, running PHP 7.2
I've re-implemented this on a server which I do believe supports the 20 MB post request. (There is no issue when running the upload test on a different browser like MS Edge, so I know it works on other browsers).

## Client
Windows 10, Firefox v 63.0

## Steps to reproduce
* Run normal test (use example-progressBar.html) with Firefox
* Wait for upload test to commence
* It should take longer than usual, loading bar will escape frame

## Expected behaviour
On Firefox, when it reaches the upload test, the results should be accurate, and the test should not take longer than usual causing the loading bar to stretch out of place.

## Screenshots
![speedtest-bug](https://user-images.githubusercontent.com/23534047/47672502-72e0fb80-db6f-11e8-84fa-eac21aae4f2f.png)

**Comment by adolfintel** [comment]
I don't see this problem on Firefox 63, did you modify something?

**Comment by adolfintel** [comment]
If you send me the URL to your server I can check it out and see if you have some config problem

**Comment by 649** [comment]
sent you an email regarding server URL

**Comment by richardkennedy** [comment]
Was this resolved? The progress bar under the Upload Gauge is running off the chart with Firefox 64.0 and Chrome 71.0.3578.98.

**Comment by adolfintel** [comment]
@richardkennedy It turned out to be a mysterious server configuration issue. What web server are you using?

**Comment by richardkennedy** [comment]
@adolfintel Apache 2.2.15. I've worked around the cosmetic issue (bar running off the chart area) by implementing the below. Based on your previous investigation, is there doubt over the validity/accuracy of the upload results?

` ctx.fillRect(c.width*0.4,c.height-16*sizScale,c.width*0.2*progress,8*sizScale);`

**Comment by adolfintel** [comment]
@richardkennedy
This problem was only reported by 2 users. One of them is this issue, and another is a guy who contacted me directly.
I was never able to replicate the problem myself, so I haven't really done much investigation. I'm sure it's something in the server configuration because he solved the issue by reinstalling apache with a clean config file, so if you changed something in your config I'd be very interested to know what you did.

The problem does affect the accuracy of the test so I don't recommend you deploy the test in this state. As for your fix, it won't be needed because in the testing branch of the speedtest I've already altered the behavior to stop a test if it runs out of time.

**Comment by richardkennedy** [comment]
@adolfintel Thanks for this. I've reviewed further and whilst I think I'm seeing similar issues, it doesn't appear to be as severe. The tests are completing within seconds and the results are consistently on-par with third party speed tests. It looks like my problem was purely with the progress bar on the upload gauge which the above fix has addressed.
