### ISSUE TITLE
Firefox does not handle ping well.

### ISSUE THREAD

**Issue by ke-mccormick** [adolfintel/speedtest#18]
Ping on FireFox is coming up 100 to 200 ms.
On Chrome the script seems to run very quickly and accurate at 20 to 30 ms.

Seems more like a browser issue, but is there something that can be optimized?

**Comment by adolfintel** [comment]
It seems almost identical to me:
![2017-02-26 11_47_05-notebot](https://cloud.githubusercontent.com/assets/16307689/23338887/5f5e6028-fc16-11e6-8627-f2e0daaa381a.png)

If you ran the test on my site, that's probably caused by the animated background, especially if you have hardware acceleration turned off (default off on linux).

**Comment by ke-mccormick** [comment]
I was using example4.html with gauges, but the upload and download seemed very responsive.

**Comment by adolfintel** [comment]
Ok, no idea why it did that then. Can you give me a link to your server?

**Comment by ke-mccormick** [comment]
I am using modified code.

I added jitter and calculations are made with a Cumulative moving average.

http://www.wiu.edu/users/mukem1/speedtest/example4.html

**Comment by adolfintel** [comment]
Cool! Can you send a pull request for the jitter calculation?
