### ISSUE TITLE
Request: Add results logging

### ISSUE THREAD

**Issue by joeyc002** [adolfintel/speedtest#202]
## Description
The ability to log speed test results

## Why it should be implemented
As an IT company, we encounter users with connection issues regularly. It would be very useful if we could send a link to our customer that is having these connection issues and the script will perform a speed test / latency test and then allow us to view the results without them having to email us back with the results. 

## Optional: implementation suggestions
Perhaps the ability to send a unique link to our customer, and it will commence the test automatically for ease of use.

**Comment by joeyc002** [comment]
I see now that it does support telemetry.

**Comment by adolfintel** [comment]
Yes, telemetry is what you're looking for. See the documentation on how to set it up on your server.

If you want the test to start automatically, simply remove the button and make the test start with the onload event of the page. If you do, I strongly suggest that you don't load external resources in your page because they would be loaded while the test is running.
