### ISSUE TITLE
Ability to double ping measurement.

### ISSUE THREAD

**Issue by ssamjh** [adolfintel/speedtest#34]
So in #33 it is mentioned that the ping amount is incorrect, and then the user says it's solved but not explaining how.

I am not very tech savvy, but is there anyway to double the ping amount shown on the page?

Speedtest site: https://speedtest.mineswine.com

**Comment by adolfintel** [comment]
Try asking him how he solved it. My guess is that it was incorrect server config.

**Comment by adolfintel** [comment]
...or you can just remove the /2 at line 325 in worker.js

**Comment by n-st** [comment]
@adolfintel Why do you divide the time by 2 anyway?

**Comment by adolfintel** [comment]
Because of how HTTP works. When you make a XHR request, here's what typically happens:
* TCP connection is created (1 RTT)
* HTTP request is sent (0.5 RTT)
* HTTP response is received (0.5 RTT)
In total, that's 2 RTT, hence the /2.
The problem is if you're using a persistent HTTP connection because only the first request takes 2 RTT, then the next ones take only 1 RTT. This typically doesn't happen for XHR though.

**Comment by n-st** [comment]
A good idea in theory, but not when your server sends a `Connection: keep-alive` header:
![2017-06-14_12-17-01](https://user-images.githubusercontent.com/2692085/27127530-ae2686b0-50fb-11e7-9353-78736e69fdc1.png)

I'd suggest making `keep-alive` mandatory for the server setup and then just discarding the first ping result (the one that establishes the connection).

**Comment by adolfintel** [comment]
Yes, that's probably a good idea.
I'll add that in the next version

**Comment by n-st** [comment]
You might also want to mention the limitations of the ping test more clearly: I came here after a hosting provider got called out for false advertising on a forum because the ping results from his speedtest page were half of what you would get from normal ping commands.

**Comment by adolfintel** [comment]
I'm sure I had that in the old version of the documentation.
Anyways, expect an update in the next few hours.
