### ISSUE TITLE
Better documentation?

### ISSUE THREAD

**Issue by Nottt** [adolfintel/speedtest#37]
Hi, I would really like to implement this as a alternative to speedtest mini, however I'm not really that good with linux and I found 0 documentation?

Would the dev be willing to release commands to copy/paste or just general documentation on how to install and run this in ubuntu 16.04 ?

**Comment by adolfintel** [comment]
Did you read doc.md?
To install on ubuntu (or any linux distro):
* install apache (https://help.ubuntu.com/lts/serverguide/httpd.html); I suggest you keep the default settings
* under /var/www (apache's root directory), make a new directory called speedtest and drop all the files there (see doc.md for details)

**Comment by Nottt** [comment]
Yes but is way too much technical. What about all that code? Don't understand anything.

I have apache installed, and I downloaded everything and copied to /var/www/html/ to a folder called speedtest...now what?

**Comment by adolfintel** [comment]
Open a browser and go to http://your.address/speedtest/example4.html (or whatever example you want to use), and you'll see it.
Note that you will need to run the test from another machine over the internet if you want to measure the speed of the internet connection.

**Comment by Nottt** [comment]
Wow that was fast! Thanks... 

Yeah accessing just server/speedtest gave me a ftp like page to download the files. 

What is the difference between those examples and which one I should use?

**Comment by adolfintel** [comment]
They're just examples showing different configurations and possible interfaces. You probably want to use example4 or example6 (just rename it to index.html).

**Comment by Nottt** [comment]
It seems to be broken, the download speed I'm 100% sure is not correct, also it will not measure Jitter...

A screenshot here : http://imgur.com/ew58H9n

**Comment by adolfintel** [comment]
Looks like PHP is not enabled on your server.
Take a look at this guide: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04#step-3-install-php

**Comment by Nottt** [comment]
Followed all of steps there, but download test will still fail. 

http://imgur.com/FAOatBt

**Comment by adolfintel** [comment]
Can you send me a link to your speedtest at dossenus91@gmail.com so I can check it?

**Comment by Nottt** [comment]
email sent

**Comment by adolfintel** [comment]
It works here. What browser are you using?

![2017-06-12 10_09_38-speedtest - chromium](https://user-images.githubusercontent.com/16307689/27024591-67ea7b52-4f57-11e7-8292-ecfc8c6f1034.png)

**Comment by Nottt** [comment]
Google Chrome Version 59.0.3071.86 (Official Build) (64-bit) on Windows 7. I do use a adblocker but it's not blocking anything on that page

**Comment by adolfintel** [comment]
I'm also using the latest Chrome and it works.
Try this:
* open the page and press F12
* select Network so we can see the connections
* run the test and see if there are any connections that failed

**Comment by Nottt** [comment]
https://i.imgur.com/C9pxl3c.png

Yeah apparently empty.php and garbage.php is failing.

**Comment by adolfintel** [comment]
Cancelled is fine, it's that ERR_CONNECTION_RESET that's weird. It only happens if there's a connection problem or if the server is not working properly.
I ran the test several times from here and it did not fail once so I guess there's a problem with the connection. What's between you and the server?

**Comment by Nottt** [comment]
PIA VPN & ISP only.

**Comment by adolfintel** [comment]
Aaaah that's the problem, as I said in the documentation, VPNs tend to cause problems with this test.
You might want to try this:
in example6, replace line 97 with this
```
w.postMessage('start {"xhr_dlMultistream": "1", "xhr_ulMultistream": "1"}')
```
This will disable the use of multiple streams, which is probably what's causing the issue with your VPN. It may negatively affect accuracy on very fast connections though (>100mbit)

**Comment by Nottt** [comment]
How bad it will affect the accuracy? Most of my users won't be behind a VPN so that won't be a issue. 

Mind I asking if you plan to workaround the VPN issue without compromising accuracy ?

Just disabled my VPN and I got my results. However they differ greatly from speedtestmini.

SpeedTest Mini says I got only 16 Mbps and your tool says 72.54 Mbit/s...

Also thanks so much for this awesome software and the fast support, let me know where I can give you a donation because good work must be recognized :)

Also would you mind if I edit your documentation for the next users? With a step by step and all

**Comment by adolfintel** [comment]
The issue with VPNs is that they perform buffering (which negatively affects mostly the upload test, appearing faster that it actually is); currently there is no workaround for this other than using WebSockets, which I am not planning to do because I want to keep this compatible with older browsers and because it requires special support server-side.

The test is accurate when you run it through the internet. I've been collecting tests for over a year now and it is now very polished. How did you get that result?

If you would like, you could write a quickstart guide for inexperienced users and send a pull request, I'm sure others will find it useful.

If you want to send a donation, that is also very appreciated, you can send it via paypal at dosse91@paranoici.org

**Comment by Nottt** [comment]
I don't understand what you meant with how I got this result? I have 120 mbps down / 20 up here...

If it's not asking too much I'm sure many users don't mind dropping support for older browsers, so if you can release a "second" test that works flawless with VPN's I'm sure many people would find it useful. There also probably more people using VPNs on the internet than really old browsers.

Also you did not answered my other questions ?

**Comment by Nottt** [comment]
I don't know how to make a pull request, but I made a quick step-by-step...if you tell me how to submit I'll do it. Just please answer my last questions and you can also close/delete this :)

**Comment by adolfintel** [comment]
Sorry I'm at work and I read your message quickly.
If you have 120/20, getting 72.54 in the download test is close but not exactly perfect. You might want to check in your modem to see the actual speed at which it is aligned with your ISP. Still, I'm getting good results from here so don't worry, you did it right.

Currently I am not planning to do that WebSocket version yet, because according to my website's stats, VPN users are less than 1% and people using IE11 are about 8%. I even got a couple of madman who tried to use IE6 from Windows 98, believe it or not. Also as I said, it needs server support, and most hosing services do not provide that yet, so you'd have to use your own server or rent a VM.

You can send me your step by step guide at dossenus91@gmail.com

P.S.: thanks for the donation ;)

**Comment by Nottt** [comment]
Is this still happening? Because I just cloned your actual repo and did tests with PIA enabled just fine...

**Comment by adolfintel** [comment]
In theory, yes, but some of the recent changes have probably improved this
