### ISSUE TITLE
Editing speedtest_worker.js settings don't apply

### ISSUE THREAD

**Issue by raxxy** [adolfintel/speedtest#38]
So I couldn't work out why I was unable to increase or decrease threadcounts, nor change chunk sizes, then when I started checking the actual requests getting sent - chunksizes don't change when changing the value away from 20. I've turned on/off quirks, forced fetch api on/off, no difference.

edit: None of the values in settings work at all. Adjusting time to 2 seconds has no effect. have restarted browser just incase.

Something broken?

**Comment by adolfintel** [comment]
Looks like you're right. They used to work before the "code restyling" pull request. I'll look into it immediately

**Comment by raxxy** [comment]
Read the docs and ran the minification. Works after doing that.

Not being able to get above 6 threads is a little disappointing (chrome restriction) but it is what it is.

It reports correctly on some 2Gbps WAN connections I have:

http://puu.sh/wmypb/0cc56e03f0.jpg

It's nearly completely accurate - right right now there's about 100Mbps of downstream traffic & 600Mbps of upstream traffic.

Latency however, isn't worth putting there. The RTT between the 2 hosts is only 0.350ms, and both hosts are 32 core machines, native, so the webserver isn't the cause of that either.

my 10Gbps stuff (same switch) it spikes to 8Gbps and then stalls immediately.

**Comment by adolfintel** [comment]
There's a guy right now who's writing a custom server for this that will be able to handle very fast connections like that 10gbps.
Meanwhile, I can confirm the issue about settings being ignored, I'm investigating it and I'll let you know.

Also, I think Chrome automatically adjusts that limit, because I've seen it using just 1-2 with a 56k modem instead of 6 on my regular DSL.

**Comment by adolfintel** [comment]
Ok, so nothing seems to have turned out from my tests. It works.
However, the part of code that's reading the custom settings is ignoring errors. Are you sure that your syntax is correct?
It should look something like this:
```js
worker.postMessage('start {"xhr_dlMultistream":"1","xhr_ulMultistream":"1"}')
```
Notice the double quotes " around both the property name and the value.
I really should make it raise a warning at least

**Comment by adolfintel** [comment]
Here's a test page to show that it's working: http://testing.fdossena.com/_test.html

**Comment by raxxy** [comment]
All I changed was the download thread count from 10 to 30 (no actual effect) and the test run time from 15 to 30, no other changes.. but when i minify/uglify, the settings do actually work

**Comment by adolfintel** [comment]
Very strange indeed, but just to be sure, I'll reupload it.
