### ISSUE TITLE
ping time wrong

### ISSUE THREAD

**Issue by belag** [adolfintel/speedtest#44]
Hi,

Great script!.
On our cpanel server the ping time is wrong for some reason. Its around 76ms whereas it should be around 12ms from my home. Jitter seems fine at around 11ms.
I have enabled the keep alive header..Any help would be appreciated :)

Regards,

Bela

**Comment by adolfintel** [comment]
First of all, try to see if empty.php returns a HTTP 200 and not a server error. Second, make sure your server doesn't take too long to respond.

Keep in mind, this is not a real ICMP ping test, it's merely measuring how long it takes for the server to send an empty document

**Comment by lgblgblgb** [comment]
Sorry for drop-in, I just have the comment, that on a server I had speedtest.net's (Ookla) mini client (yet back a flash solution). On the really same server installed this awesome HTML based project. What I can see, that (Ookla's) speedtest always reports something like 20msec, however your one reports anything in the range of 60-350 (quite hard to tell, it varies a lot). But honestly I've tested with firefox (version 54) only, on Linux, and with the example htmls. The measured bandwidth values are quite consistent and good ones (though a bit higher than Ookla's but maybe that's because of those "correction' values doc.mk writes about too - I have to test it later), but not the ping. If my comment is not so useful here, just forget it. :)

**Comment by adolfintel** [comment]
Can you give me the address of your server so I can see if there is anything obvious?
The most common causes for this high and variable ping are:
* Server is not keeping the connection alive after sending empty.php
* Server is slow or is throttling the number of requests
* Server is replying with an error message instead of empty.php when it's requested (I've had this problem on my own website for a few weeks before I noticed)

**Comment by lgblgblgb** [comment]
It's a bit problematic, because it's a server at my workplace dedicated to the in-network customers speed test can be accessed only in the VLAN users are attached to ... But I try to find a public server to test if it's the same and post here if similar things found. One note though: in firefox now I left network console open during the test. What I've found that requests for empty.php about 10-15ms according to the network console all the time, though the page reported 600ms (!) as ping time. I guess it can be, that firefox used time for the console as well? Note: though it's firefox v54, I switched multiprocess stuff off, since it used extremely too much memory for my every day work with the usual 60 browser TABs I use with 4Gbyte of memory (that's why I don't use chrome: too much memory hunger ...). But, surely, for this test now, I hadn't got many tabs open and browser had been restarted just before.

**Comment by lgblgblgb** [comment]
Ok, with chrome, the ping is much smaller, quite normal. With firefox (note about the switched multiprocess mode off, I've talked about) is far more worse about the double, and if I have network console open, and it's even more worse. The measured bandwidth though seems to be about the same with both of chrome/firefox, console open or not ...

**Comment by adolfintel** [comment]
Ok, so something is making your firefox browser lag, any ideas?

**Comment by lgblgblgb** [comment]
Not so much ... yet ... Just I have the idea, that if firefox _knows_ what is the "true" latency of "getting" empty.php (and it seems it does, since network monitor never reports more than 20ms for the that request), then is it possible somehow that the measurement used get the correct value as well. What I think here actually, that it was mentioned before (sorry, maybe not in this bugreport, but in an older one which is already closed, now I can't find ...) that "slow drawing" done by the browser can cause that, isn't that possible to measure the value and make the actual page rendering etc totally separated from the measurement stuff? But sorry if I talk non-sense here, since it seems it uses html5 workers already to do the serious stuff in the "background" if I can say this way ...

**Comment by adolfintel** [comment]
You're not talking nonsense.
That is something that I had tried but unfortunately firefox keeps those stats for itself (and chrome too), so the only way to know how long a request took is to take a timestamp when you send it and another one when the reply comes back. The problem is, firefox seems to tie these events to the rendering of the page, which is why I used web workers in the first place, because I hoped that it would workaround this issue of slow rendering, but it looks like firefox is still tied to its main thread.
I'm sure that they'll make firefox completely multithreaded soon, so for the moment, just know that the test will work for 99% of your users. From the stats I've collected on my website, this issue affects only about 10% of firefox users on linux (so less than 1% of the global population), I guess it's the ones who have hardware acceleration turned off for driver issues.

**Comment by lgblgblgb** [comment]
Sorry for the message after closed ticket, just one comment: I tried to put a stupid test together, with using the window.performance object for measure the time for "ping" (I thought it may be handled differently etc), but the very same result, maybe no wonder, and I had only unrealistic hopes :-O

**Comment by adolfintel** [comment]
Yes I tried using window.performance too

**Comment by adolfintel** [comment]
Don't worry too much, I'm sure firefox will be fully mulltithreaded soon, especially after they'll release the new engine

**Comment by lgblgblgb** [comment]
I'm just curious how other "clear" (not flash etc) HTML5 based tests from others can solve this, eg speedtest.net's newer html5-only solution ... But I guess they may not want us to know and try to hide as much as possible .... :-O

**Comment by adolfintel** [comment]
I have no idea honestly, that would require some reverse engineering
