### ISSUE TITLE
List of (non-)supported browsers

### ISSUE THREAD

**Issue by MrkSmt** [adolfintel/speedtest#59]
It would be nice to have a list of the versions that don't support the speedtest. So that I can block these browsers for reaching the speedtest. In this way they don't get to a speedtest that doesn't work on the browser that they are using.

**Comment by adolfintel** [comment]
Technically, the test requires Web Workers and XHR Level 2 to work, so if you check for those you'll be correct 99% of the time.
Like most other web projects, I test on the latest version of each major browser, so I cannot guarantee that it works flawlessly on older versions.
From the project's history, I can tell you that this works on IE11, all versions of Edge, Chrome since 42 (and chromium based), all versions of Firefox since 38 ESR.

**Comment by MrkSmt** [comment]
Thank you for the quick answer. When I search for the XHR level 2 support I get the following list of notes:
- Partial support refers to not supporting `json` as `responseType`
- Partial support refers to not supporting `.timeout` and `.ontimeout`
- Partial support refers to not supporting `blob` as `responseType`

Is the speedtest using one of these things? If so I can also block the browsers that don't have support for that.

**Comment by adolfintel** [comment]
`blob` is used.
But please do not check the user agent, check for those 2 features.
