### ISSUE TITLE
Download test no completed

### ISSUE THREAD

**Issue by unixjeff** [adolfintel/speedtest#6]
When running the test the upload and ping work but the download does not, tried using a 500mb (empty.dat) and still no luck

**Comment by adolfintel** [comment]
The ping test surely won't work if you're using a 500mb file because it will attempt to download it. It's probably the same thing with the upload.
If you want to use a file instead of the script, you should point to that file only for the download test. The upload and ping test should upload to an empty file. Also, your server must accept relatively large POST requests for the upload test.
Let me know if you need help.

**Comment by unixjeff** [comment]
Should the html file be updated replacing garbage.php with the large file?

 "url_dl":"garbage.php",

**Comment by adolfintel** [comment]
Yes

**Comment by unixjeff** [comment]
Should the html file be updated replacing garbage.php with the large file?

 "url_dl":"garbage.php",

**Comment by unixjeff** [comment]
Worked perfectly! Thank you
