### ISSUE TITLE
Possible Problem With Download Speed?

### ISSUE THREAD

**Issue by TheEagle13** [adolfintel/speedtest#67]
I'm noting a trend that no matter where I host this, I never get more than 3 Mbit/s for download speed. (Locally, or on a 100 MBPS VPS across the Internet). I've also noticed when I did the demo on your site, my download speed is also never more than 3 Mbit/s (It always hovers wight at 3, but never goes above that). Considering I was getting 500 Mbit/s upload speed in my lan, I think something might be off here.

(Ping and jitter also seem to be off for what a LAN should be too...)
![screenshot](https://user-images.githubusercontent.com/32144818/30665554-f95156a2-9e16-11e7-9b7e-51ad62ac00cc.png)
 

Any suggestions?

**Comment by adolfintel** [comment]
garbage.php is not reachable, not working or PHP is not installed.
Make sure that
* PHP 5.3 or newer is installed
* garbage.php is not throwing a 404, 500 or any other error
* OpenSSL is installed, with the PHP plugin (usually distros already install it with PHP but you never know)
I'll close the issue since this is the most typical installation error, but feel free to write if you need help setting it up.

**Comment by TheEagle13** [comment]
See, now I read that in the readme, and I have verified that none of those are the case. The thing that leeds me to think it's a bug is because it happens on your hosted speedtest site too.

**Comment by adolfintel** [comment]
Oh, that's weirr.
I'm going to need some info on this; it never happened in 1.5 years.
* what browser are you using?
* your os
* is the browser laggy during the test?

**Comment by lgblgblgb** [comment]
Sorry for interrupting the work here, but I think to handle these "not even PHP installed" etc issue would be to do a check by the measurement JS code. What I mean that one of the first thing it can do is doing a HTTP request "towards a PHP file" (eg as the part of the getIP thinggy, or other?). Eg it should print (done in PHP) an ID-string fist. If PHP is not installed, the web server would simply stream the source of the PHP file (ie starting with <?php etc) and not the "id-string", so the JS code can abort the whole process and clearly stating that server side PHP problem detected. Oh yes, and it can even give information if the needed OpenSSL function is defined. I don't even mention the possibility that giving only the REMOTE_ADDR back, it can report http headers got suspecting a proxy (X-Forwarded-For and similar, now I tell these only by heart!) so again, it's possible to report by the page that it's a sub-optimal situation since it's suspected that a HTTP proxy in a way, which can affect the performance a lot, thus giving quite bogus results .... This "checking the server side" first stuff can be really combined with the remote addr IP check, maybe with other functions implemented in the server side optionally (eg a crude, not so precise mechanism to warn the page that the server is on high network load so the result can be incorrect ... of course it needs a server specific setup and method, so it's greatly optional and user's TODO then). I just write these if it's useful at all. We have (at my workplace) an own in-house development for speed testing with similar features, though, unfortunately I can't share the code, since it's not an open source project, and also not exactly my "property" to do. But this project here seems to be kind of superior already in many aspects at least :) :)

**Comment by adolfintel** [comment]
I was thinking of having like a "diagnostic mode". It seems wasteful to put these checks in the speedtest itself, but a test page that checks if it's configured properly is totally coming in the next version.

**Comment by adolfintel** [comment]
By the way, I was looking at the telemetry from my test, looking for results with download<4 and upload>50.
The most recent is from 2017-09-18, Firefox 55 on Mac, russian, download 3.01, upload 51.18. Is that you @TheEagle13 ?
I have other tests from similar configurations but they all look fine.
