### ISSUE TITLE
Just an idea: usage of PerformanceTiming API

### ISSUE THREAD

**Issue by lgblgblgb** [adolfintel/speedtest#70]
Just an idea: I didn't know about this, just I happened to hit that page by browsing firefox's sites: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming
Interesting. Can it be useful for more accurate measurement? It seems there are timestamps about the last request/response, at various stages (and the delay between them can be easily done with subtracting, of course). I wonder, if it's more accurate than to do date query from JS caused by some JS events listened to. I'm not sure though, how standard the PerformanceTiming interface in various browsers. Hopefully this post here was useful, if no, just close it without answer, for sure.

**Comment by adolfintel** [comment]
I already tried to do this but ran into some problems.
This would be useful to improve the accuracy of the ping/jitter test, especially if the browser is lagging. It would be no good for the download and upload tests because it provides no information about ongoing XHRs, only completed ones.
I didn't go through with it because it was simply not stable: all browsers seem to implement the Performance API differently, especially the older ones, so it would require extensive testing and probably a lot of "quirks" just to get a marginal improvement on accuracy.
That said, I still have the code so in the future I might add it as an option or something.
