### ISSUE TITLE
is it possible to set QoS ?

### ISSUE THREAD

**Issue by trips1990** [adolfintel/speedtest#71]
is it possible to set 10/20/50 mbps QoS in the tool for both upload/download speed ?

**Comment by trips1990** [comment]
My speedtest server is behind a firewall. I have tried setting Qos to 10mbps for upload/download.
I am getting 10mpbs for download but around 30mpbs for upload.

Can you guide me how this can be achieved.

**Comment by adolfintel** [comment]
The speedtest itself cannot be modified to do this. You can achieve this with your firewall but it's not that easy: the speedtest uses a variable number of connections both during the tests, so you can't just limit the speed of the single TCP connections, you need a global limit for all connections from/to that client.
Also, you should make sure that your firewall doesn't queue too many incoming packets, otherwise the upload will appear higher to the client.
