### ISSUE TITLE
as measured speeds less than 1 Mb?

### ISSUE THREAD

**Issue by armandofelipe1992** [adolfintel/speedtest#82]
I have connections by modem and I would like to measure the speed of the same as it modified the system so that it can know the speed that reached

**Comment by adolfintel** [comment]
I don't understand, what do you want to do?
You want more precision for very low speeds?

**Comment by armandofelipe1992** [comment]
I want to measure the speed in connections less than 1MB ie to measure the speed in Kbs

**Comment by armandofelipe1992** [comment]
I'm using speedtest_worker.min.js
and example2.html

**Comment by adolfintel** [comment]
Oh, ok.
The speed is measured in mb/s with 2 decimals by the test. The accuracy is fixed, it does not switch from kb/s to mb/s. This is to avoid confusion when reading the results.
If you want it to be in kb/s instead of mb/s, you have to:
* Edit speedtest_worker.js, at lines 235 and 351, replace 1048576 with 1024.
* Edit example2.html at line 66, replace .min.js with just .js; and all the Mbit/s with Kbit/s
