### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by saldru** [adolfintel/speedtest#86]
Hi,

First, thank you for your work !

I want to propose some improvements that could be interesting to add to the speedtest. 

My ideas of improvements are based on the nPerf webserver ([https://www.nperf.com](https://www.nperf.com)).

- It could be interesting to add ISP informations like the name of the ISP and the AS Number. You can use a javascript script and take informations with the API of some website like [https://ipinfo.io](https://ipinfo.io).

- In the same time, add the location of the IP address and the country with a flag and the name of the country for example.

- For the IP addresses, it could be interesting to separate this function in two for IPv4 and IPv6. If the customer doesn't have an IPv6 address, write "No" in red color for example. And the same if the customer doesn't have an IPv4 address.

- I don't know if it's possible but it can be more beautiful to view a progress bar with multicolor like a progress bar that start in blue, pass by green, next by yellow and finish by red. Maybe make the inverse for the latence and the jitter.

- Next possible improvement it's to allow the customer to change unit for bandwidth. You have Mbps, but some people want to have bandwidth in MBytes. 

I hope that my ideas can help you to maybe improve the speedtest functionnalities. 

Thank's again for your work. :)
Saldru

**Comment by adolfintel** [comment]
All of these are doable except the IPv4/IPv6 thing I think, because when you send a request to getIP.php you can only get the address of the connection that sent the request, so you'll only back whatever address sent the request, regardless of IPv4/6.
Progress bars are coming in the next version, which should be ready in 1-2 days.
The other suggestions might come in future versions, especially the ISP info which was already implemented by a fork of this project I think.
